packages:
  - packages/*
  - libs/*
  - apps/*
catalog:
  '@xsai-ext/providers-cloud': ^0.2.1
  '@xsai/embed': ^0.2.1
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - bufferutil
  - core-js
  - es5-ext
  - esbuild
  - keccak
  - scrypt
  - secp256k1
  - sha3
  - utf-8-validate
  - vue-demi
onlyBuiltDependencies:
  - nodejieba
  - websocket
